services:

  mysql:
    image: mysql:8.4
    container_name: eventtickets-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: mysql2002
      MYSQL_DATABASE: eventsDB

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmysql2002"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./EventTicketsApp

    container_name: eventtickets-backend
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8086:8086"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql2002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./event-tickets-frontend

    container_name: eventtickets-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "4200:80"

volumes:
  mysql-data: